// Copyright CodeGamified 2025-2026
// MIT License — PopVuj
//
// Sky dome shader — samples the composited sky RenderTexture
// on a world-space inverted hemisphere mesh generated by SkyRenderer.
//
// Mesh UV: U = azimuth (0..1 wrapping), V = elevation (0=horizon, 1=zenith).
// Cull Front = render inner (concave) surface only.
// Background queue, ZWrite Off — renders before all scene geometry.

Shader "PopVuj/Skybox"
{
    Properties
    {
        _SkyTex ("Sky Composite", 2D) = "black" {}
    }

    SubShader
    {
        Tags { "Queue"="Background" "RenderType"="Background" }
        Cull Front
        ZWrite Off

        Pass
        {
            CGPROGRAM
            #pragma vertex vert
            #pragma fragment frag
            #include "UnityCG.cginc"

            sampler2D _SkyTex;

            struct appdata
            {
                float4 vertex : POSITION;
                float2 uv     : TEXCOORD0;
            };

            struct v2f
            {
                float4 pos : SV_POSITION;
                float2 uv  : TEXCOORD0;
            };

            v2f vert(appdata v)
            {
                v2f o;
                o.pos = UnityObjectToClipPos(v.vertex);
                o.uv  = v.uv;
                return o;
            }

            half4 frag(v2f i) : SV_Target
            {
                return tex2D(_SkyTex, i.uv);
            }
            ENDCG
        }
    }
}
